assignment/urls.py
from django.urls import path
from .views import *

app_name='assignment'
urlpatterns = [
	path('', adminIndex.as_view(), name='admin-index'),
    path('userlist/<int:pk>', userList.as_view(), name='userlist'),
    path('userprofile/<int:pk>', userProfile.as_view(), name='userprofile'),
    path('department-list', DepartmentList.as_view(), name='department-list'),
    path('rolelist', RolesListView.as_view(), name='rolelist'),
    path('unassigned-list', unassignedUserList.as_view(), name='unassigned-list'),
    # path('assign-dept-manager', departmentManagerCreateView.as_view(), name='assign-dept-manager'),
    # path('update-dept-manager/<int:pk>', departmentManagerUpdateView.as_view(), name='update-dept-manager'),
    # path('delete-dept-manager/<int:pk>', departmentManagerDeleteView.as_view(), name='delete-dept-manager'),
]

core/urls.py
from django.urls import path
from .views import *
from register import views as register_views

app_name='core'
urlpatterns = [
    path('',index, name='index'),
    path('add-personal-info', EPICreateView.as_view(), name='add-personal-info'),
    path('add-education-info', EEICreateView.as_view(), name='add-education-info'),    
    path('add-experience-info', EExICreateView.as_view(), name='add-experience-info'),    
    path('profile', profile, name='profile'),
    path('update-personal-info/<int:pk>', EPIUpdateView.as_view(), name='update-personal-info'),
    path('update-profile-pic/<int:pk>', ProfilePicIUpdateView.as_view(), name='update-profile-pic'),
    path('task-review-details/<int:pk>', TaskReviewDeailView.as_view(), name='task-review-details'),
    path('manager-dashboard', ManagerDashboard.as_view(), name='manager-dashboard'),
    path('department-information', DepartmentInformation.as_view(), name='department-information'),
    path('task-list/<int:pk>', TaskList.as_view(), name='task-list'),
    path('task-details/<int:pk>', TaskDeailView.as_view(), name='task-details'),
    path('emp-performance/<int:pk>', EmpPerformance.as_view(), name='emp-performance'),

    path('register', register_views.register, name='register'),
    # path('login/', LoginView.as_view(), name='login'),

    path('admincrud/', AdminCrud.as_view(), name='admincrud'),

    
]

createMode/urls.py
from django.urls import path
from .views import *

app_name='createMode'
urlpatterns = [
    path('department', DepartmentCreateView.as_view(), name='create-departent'),
    path('department-update/<int:pk>', DepartmentUpdateView.as_view(), name='update-department'),
    path('jobinfo-update/<int:pk>', JobInfoUpdateView.as_view(), name='jobinfo-update'),
    path('jobinfo-create', JobInfoCreateView.as_view(), name='jobinfo-create'),
    path('create-task', TaskCreateView.as_view(), name='create-task'),
    path('user-create-task/<int:pk>', UserTaskCreate.as_view(), name='user-create-task'),    
    path('update-task/<int:pk>', TaskUpdateView.as_view(), name='update-task'),
    path('assign-task/<int:pk>', TaskAssignView.as_view(), name='assign-task'),
    path('task-review/<int:pk>', ReviewTask.as_view(), name='task-review'),
    path('submit-task/<int:pk>', submitTaskCreateView.as_view(),name='submit-task'),
    path('role', RoleCreateView.as_view(), name='create-role'),
    path('accept-task/<int:pk>', TaskAcceptView.as_view(),name='accept-task'),
    path('reject-task/<int:pk>', TaskRejectView.as_view(),name='reject-task'),
    path('rejected-feedback/<int:pk>', TaskRejectDetailsView.as_view(),name='rejected-feedback'),

]

performance/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('ad/', include('assignment.urls')),
    path('create/', include('createMode.urls')),
    path('', include("django.contrib.auth.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

assignment/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, TemplateView, CreateView, UpdateView, DeleteView
from django.contrib.auth.models import User
from core.models import *

class AdminRequiredMixin(object):
    def dispatch(self, request, *args, **kwargs):
        usr = request.user
        if usr.is_authenticated and usr.is_superuser:
            pass
        else:
            return redirect('core:index')

        return super().dispatch(request, *args, **kwargs)


class adminIndex(AdminRequiredMixin, TemplateView):
	template_name = "assignment/index.html"

class userList(AdminRequiredMixin, ListView):
	template_name = "assignment/userlist.html"
	model = EmployeePersonalInfo

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)    
		department = Department.objects.get(pk= self.kwargs['pk'])
		job_info = EmployeeJobInfo.objects.filter(department = department)
		employee_info = []
		for user in job_info:
			info = EmployeePersonalInfo.objects.get(user =user.user)
			emp_info = {
				'username' : info.user.username,
				'fullname' : info.fullname,
				'age' : info.age,
				'address' : info.address,
				'pk' : info.pk,
				'department' : department,
				'job_title' : user.job_title,
				'rank' : user.rank,
				'working_hours' : user.working_hours,
				'roles' : user.roles,
				'isManager' : user.isManager,
				'user_pk' : user.pk
			}
			employee_info.append(emp_info)
		context['employee_info'] = employee_info

		return context

class userProfile(AdminRequiredMixin, ListView):
	template_name = "core/profile.html"
	model = User

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)   
		context['personal_info'] = EmployeePersonalInfo.objects.get(pk= self.kwargs['pk'])
		context['user_info'] = context['personal_info'].user
		try:
			context['job_info'] = EmployeeJobInfo.objects.get(user=user_info)
		except:
			context['job_info'] = {
				'department' : 'N/A',
				'job_title' : 'N/A',
				'rank' : 'N/A',
				'working_hours' : 'N/A',
				'roles' : 'N/A',
				'Pay_Grade' : 'N/A'
			}
		if self.request.user != context['user_info']:
			context['is_logged_profile'] = False
		return context

class RolesListView(AdminRequiredMixin, ListView):
	model = Role
	context_object_name = 'roles'
	template_name = "assignment/roles_list.html"


class DepartmentList(AdminRequiredMixin, ListView):
	template_name = "assignment/departmentlist.html"
	model = Department
	context_object_name = 'department'

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)    
		context['department'] = Department.objects.all()
		context['department_count'] = []
		context['dept_manager'] = []
		for dept in context['department']:
			dept_manager = {
				'department_name': dept.name,
				'dept_manager' : DepartmentManager.objects.filter(department=dept)
			}
			count = {
				'department_name': dept.name,
				'count' : EmployeeJobInfo.objects.filter(department=dept).count(),
				'dept_manager' : EmployeeJobInfo.objects.filter(department=dept).filter(isManager=True)
			}
			context['dept_manager'].append(dept_manager)
			context['department_count'].append(count)
		return context

class unassignedUserList(AdminRequiredMixin, ListView):
	template_name = "assignment/userlist.html"
	model = EmployeePersonalInfo

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)    
		job_info = EmployeeJobInfo.objects.filter(department=None)
		employee_info = []
		for user in job_info:
			info = EmployeePersonalInfo.objects.get(user =user.user)
			emp_info = {
				'username' : info.user.username,
				'fullname' : info.fullname,
				'age' : info.age,
				'address' : info.address,
				'pk' : info.pk,
				'department' : user.department,
				'job_title' : user.job_title,
				'rank' : user.rank,
				'working_hours' : user.working_hours,
				'roles' : user.roles,
				'isManager' : user.isManager,
				'user_pk' : user.pk
			}
			employee_info.append(emp_info)
		context['employee_info'] = employee_info
		return context


# For seperate dept manager model system
# class departmentManagerCreateView(AdminRequiredMixin, CreateView):
# 	model = DepartmentManager
# 	fields = ['department', 'user']
# 	template_name = "assignment/assign_manager.html"
# 	success_url = reverse_lazy('assignment:department-list')

# class departmentManagerUpdateView(AdminRequiredMixin, UpdateView):
# 	model = DepartmentManager
# 	fields = ['department', 'user']
# 	template_name = "assignment/update_manager.html"
# 	success_url = reverse_lazy('assignment:department-list')

# 	def get_context_data(self, **kwargs):
# 		context = super().get_context_data(**kwargs)   
# 		context['dept_pk'] = self.kwargs['pk']

# 		return context

# class departmentManagerDeleteView(AdminRequiredMixin, DeleteView):
# 	model = DepartmentManager
# 	template_name = "assignment/delete_manager.html"
# 	success_url = reverse_lazy('assignment:department-list')

assignment/templates/assignment/assign_manager.html
{% extends 'core/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
	
	<div style="margin-left: 20%; margin-right: 20%; text-align: center">
		{% if messages %}
       		{% for message in messages %}

     			<div class="alert alert-{{ message.tags }}">
         			{{ message }}
				</div>

         	{% endfor %}
        {% endif %}
	</div>

	<div class="infoupdateform container">
		<h3>Assign Department Manager</h3>
		<form method="POST" class="form-group">
			{% csrf_token %}
			{{ form|crispy }}
			<button type="submit" class="btn btn-success">Submit</button>
		</form>
	</div>	

{%  endblock %}

assignment/templates/assignment/delete_manager.html
{% extends 'core/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
	
	<div style="margin-left: 20%; margin-right: 20%; text-align: center">
		{% if messages %}
       		{% for message in messages %}

     			<div class="alert alert-{{ message.tags }}">
         			{{ message }}
				</div>

         	{% endfor %}
        {% endif %}
	</div>

	<div class="infoupdateform container">
		<h3>Are you sure you want to remove {{ object.user.username }} from Department Manager </h3>
		<form method="POST" class="form-group">
			{% csrf_token %}
			{{ form|crispy }}
			<button type="submit" class="btn btn-danger">Remove</button>
		</form>
	</div>	

{%  endblock %}

assignment/templates/assignment/departmentlist.html
{% extends 'core/base.html' %}

{% block content %}

	<h1>Department List</h1>
	<br>
	<a class='add-dept' href="{% url 'createMode:create-departent' %}">
		Add new department
	</a>
	<a class='add-dept' href="{% url 'assignment:unassigned-list' %}">
		View unassigned users
	</a>
	<table>
		<tr>
			<th>Department Name</th>
			<th>Description</th>
			<th>Manager</th>
			<th>No. of employees</th>
			<th></th>
		</tr>
			{% for department in department %}
				<tr>
			    	<td> <a href="{% url 'assignment:userlist' department.pk %}">
			    		{{ department.name}}
			    	</a></td>
			    	<td> {{ department.description }}</td>
			    	<td>
						{% for dept in department_count  %}
							{% if dept.department_name == department.name %}
								{% for manager in dept.dept_manager %}
									{{ manager.user.username }}
									&nbsp;
									<a href="{% url 'createMode:jobinfo-update' manager.pk %}"><i class="fas fa-cog"></i></a>
								 <br>
								{% endfor %}
							{% endif %}
					{% endfor %} 
			    	</td>
			    	<td> 
			    		{% for dept in department_count  %}
							{% if dept.department_name == department.name %}
								{{ dept.count }}
							{% endif %}
					{% endfor %}
			    	</td>
			    	<td>
			    		<a href="{% url 'createMode:update-department' department.pk %}">Update</a>
			    	</td>
			    </tr>
			{% endfor %}
	</table>	



{% endblock %}

assignment/templates/assignment/index.html
{% extends 'core/base.html' %}

{% block content %}

	<div style="text-align: center; margin-top: 55px">
		<a style="" href="{% url 'assignment:department-list' %}"><h2> Department List </h2></a>
		<a style="" href="{% url 'createMode:create-departent' %}"><h4> Add new department </h4></a>
		<a style="" href="{% url 'assignment:unassigned-list' %}"><h4> View unassigned users </h4></a>
	</div>

	<div style="text-align: center; margin-top: 55px">
		<a style="" href="{% url 'assignment:rolelist' %}"><h2> Roles List </h2></a>
		<a style="" href="{% url 'createMode:create-role' %}"><h4> Add new role </h4></a>
	</div>

	<div style="text-align: center; margin-top: 55px">
		<a style="" href="{% url 'createMode:jobinfo-create' %}"><h1> Create job Info </h1></a>
	</div>


{% endblock %}

assignment/templates/assignment/roles_list.html
{% extends 'core/base.html' %}

{% block content %}

	<h3>Roles</h3>

	<br>
	<a class='add-dept' href="{% url 'createMode:create-role' %}">
		Add new Role
	</a>

	<table>
		<tr>
			<th>Name</th>
			<th>Description</th>
			<th></th>
		</tr>
			{% for role in roles %}
				<tr>
			    	<td> 
			    		{{ role.name }}
			    	</td>
			    	<td> {{ role.description }}</td>
			    	<td>
			    	</td>
			    </tr>
			{% endfor %}
		
	</table>

{% endblock %}

assignment/templates/assignment/update_manager.html
{% extends 'core/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
	
	<div style="margin-left: 20%; margin-right: 20%; text-align: center">
		{% if messages %}
       		{% for message in messages %}

     			<div class="alert alert-{{ message.tags }}">
         			{{ message }}
				</div>

         	{% endfor %}
        {% endif %}
	</div>

	<div class="infoupdateform container">
		<h3>Update Department Manager</h3>
		<form method="POST" class="form-group">
			{% csrf_token %}
			{{ form|crispy }}
			<button type="submit" class="btn btn-success">Submit</button>
		</form>
	</div>	

{%  endblock %}

assignment/templates/assignment/userlist.html
{% extends 'core/base.html' %}

{% block content %}

	<h3>User List</h3>

				<div class="box-element">
					<a class="btn btn-outline-light" href="{% url 'assignment:department-list' %}">&#x2190; 
					Go Back
					</a>

				</div>

	<table>
		<tr>
			<th>username</th>
			<th>Full Name</th>
			<th>Department</th>
			<th>Project</th>
			<th>Job title</th>
			<th>Rank</th>
			<th>Role</th>
			<th>Hours</th>
			<th>isManager</th>
			<th></th>
		</tr>
			{% for object in employee_info %}
				<tr>
			    	<td> <a href="{% url 'assignment:userprofile' object.pk %}">
			    		{{ object.username}}
			    	</a></td>
			    	<td> {{ object.fullname }}</td>
			    	<td>{{ object.department }}</td>
			    	<td> To be added </td>
			    	<td>{{ object.job_title }}</td>
			    	<td> {{ object.rank }} </td>
			    	<td> {{ object.roles }} </td>
			    	<td> {{ object.working_hours }} </td>
			    	<td> {{ object.isManager }}</td>
			    	<td>
			    		<a href="{% url 'createMode:jobinfo-update' object.user_pk %}">Update job info</a>
			    	</td>
			    </tr>
			{% endfor %}
		
	</table>

{% endblock %}