assignment/urls.py
from django.urls import path
from .views import *

app_name='assignment'
urlpatterns = [
	path('', adminIndex.as_view(), name='admin-index'),
    path('userlist/<int:pk>', userList.as_view(), name='userlist'),
    path('userprofile/<int:pk>', userProfile.as_view(), name='userprofile'),
    path('department-list', DepartmentList.as_view(), name='department-list'),
    path('rolelist', RolesListView.as_view(), name='rolelist'),
    path('unassigned-list', unassignedUserList.as_view(), name='unassigned-list'),
    # path('assign-dept-manager', departmentManagerCreateView.as_view(), name='assign-dept-manager'),
    # path('update-dept-manager/<int:pk>', departmentManagerUpdateView.as_view(), name='update-dept-manager'),
    # path('delete-dept-manager/<int:pk>', departmentManagerDeleteView.as_view(), name='delete-dept-manager'),
]

core/urls.py
from django.urls import path
from .views import *
from register import views as register_views

app_name='core'
urlpatterns = [
    path('',index, name='index'),
    path('add-personal-info', EPICreateView.as_view(), name='add-personal-info'),
    path('add-education-info', EEICreateView.as_view(), name='add-education-info'),    
    path('add-experience-info', EExICreateView.as_view(), name='add-experience-info'),    
    path('profile', profile, name='profile'),
    path('update-personal-info/<int:pk>', EPIUpdateView.as_view(), name='update-personal-info'),
    path('update-profile-pic/<int:pk>', ProfilePicIUpdateView.as_view(), name='update-profile-pic'),
    path('task-review-details/<int:pk>', TaskReviewDeailView.as_view(), name='task-review-details'),
    path('manager-dashboard', ManagerDashboard.as_view(), name='manager-dashboard'),
    path('department-information', DepartmentInformation.as_view(), name='department-information'),
    path('task-list/<int:pk>', TaskList.as_view(), name='task-list'),
    path('task-details/<int:pk>', TaskDeailView.as_view(), name='task-details'),
    path('emp-performance/<int:pk>', EmpPerformance.as_view(), name='emp-performance'),

    path('register', register_views.register, name='register'),
    # path('login/', LoginView.as_view(), name='login'),

    path('admincrud/', AdminCrud.as_view(), name='admincrud'),

    
]

createMode/urls.py
from django.urls import path
from .views import *

app_name='createMode'
urlpatterns = [
    path('department', DepartmentCreateView.as_view(), name='create-departent'),
    path('department-update/<int:pk>', DepartmentUpdateView.as_view(), name='update-department'),
    path('jobinfo-update/<int:pk>', JobInfoUpdateView.as_view(), name='jobinfo-update'),
    path('jobinfo-create', JobInfoCreateView.as_view(), name='jobinfo-create'),
    path('create-task', TaskCreateView.as_view(), name='create-task'),
    path('user-create-task/<int:pk>', UserTaskCreate.as_view(), name='user-create-task'),    
    path('update-task/<int:pk>', TaskUpdateView.as_view(), name='update-task'),
    path('assign-task/<int:pk>', TaskAssignView.as_view(), name='assign-task'),
    path('task-review/<int:pk>', ReviewTask.as_view(), name='task-review'),
    path('submit-task/<int:pk>', submitTaskCreateView.as_view(),name='submit-task'),
    path('role', RoleCreateView.as_view(), name='create-role'),
    path('accept-task/<int:pk>', TaskAcceptView.as_view(),name='accept-task'),
    path('reject-task/<int:pk>', TaskRejectView.as_view(),name='reject-task'),
    path('rejected-feedback/<int:pk>', TaskRejectDetailsView.as_view(),name='rejected-feedback'),

]

performance/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('ad/', include('assignment.urls')),
    path('create/', include('createMode.urls')),
    path('', include("django.contrib.auth.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import RegexValidator

gender_choices = [
    ('M', 'Male'),
    ('F', 'Female'),
    ('O', 'Others')
]
working_hours_choices = [
	('F', 'Full Time'),
	('P', 'Part Time'),
	('c', 'Contract Based')
]
rank_choices = [
	('I', 'Intern'),
	('J', 'Junior'),
	('M', 'Mid-level'),
	('S', 'Senior')
]

class EmployeePersonalInfo(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	fullname = models.CharField(max_length=50)
	gender = models.CharField(max_length=25, choices=gender_choices)
	age = models.IntegerField()
	image = models.ImageField(default="default.png", upload_to='profile_pics')
	address = models.CharField(max_length=50)
	phone_number = models.CharField(max_length=15, validators=[RegexValidator(r'^\d{1,15}$')])

	def __str__(self):
		return self.user.username

class EmployeeEducationInfo(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	university = models.CharField(max_length=50)
	degree = models.CharField(max_length=50)
	faculty = models.CharField(max_length=50)
	graduatation_year = models.DateField()

	def __str__(self):
		return self.user.username

class EmployeeExperienceInfo(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	experience_in_years = models.IntegerField()
	no_of_previous_company = models.IntegerField()
	jobtitle_at_previous = models.CharField(max_length=50)

	def __str__(self):
		return self.user.username

class Department(models.Model):
	name = models.CharField(max_length=60)
	description = models.CharField(max_length=264)
	

	def __str__(self):
		return self.name

class Role(models.Model):
	name = models.CharField(max_length=60)
	description = models.CharField(max_length=264)

	def __str__(self):
		return self.name

class PayGrade(models.Model):
	grade = models.CharField(max_length=60)
	amount = models.PositiveIntegerField()

	def __str__(self):
		return self.grade

class EmployeeJobInfo(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	job_title = models.CharField(max_length=50)
	rank = models.CharField(max_length=25, choices=rank_choices)
	working_hours = models.CharField(max_length=25, choices=working_hours_choices)
	department = models.ForeignKey(Department, on_delete=models.SET_NULL, blank=True, null=True)
	roles = models.ForeignKey(Role, on_delete=models.SET_NULL, blank=True, null=True)
	Pay_Grade = models.ForeignKey(PayGrade, on_delete=models.SET_NULL, blank=True, null=True)
	isManager = models.BooleanField(default=False)

	def __str__(self):
		return self.user.username

class DepartmentManager(models.Model):
	department = models.ForeignKey(Department, on_delete=models.CASCADE)
	user = models.OneToOneField(User, on_delete=models.SET_NULL, blank=True, null=True)

	def __str__(self):
		return f'{self.department.name}-{self.user.username}'

core/forms.py
from django import forms
from .models import *

class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput())

core/views.py
from django.shortcuts import render,redirect
from django.views import View 
from django.views.generic import ListView, DetailView, CreateView, UpdateView,DeleteView, TemplateView, FormView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth import authenticate, login


from .models import *
from createMode.models import *
from .forms import * 
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Sum



class AdminRequiredMixin(object):
    def dispatch(self, request, *args, **kwargs):
        usr = request.user
        if usr.is_authenticated and usr.is_superuser:
            pass
        else:
            return redirect('/register/')

        return super().dispatch(request, *args, **kwargs)

class ManagerRequiredMixin(object):
    def dispatch(self, request, *args, **kwargs):
        usr = request.user
        usr_job_info = EmployeeJobInfo.objects.get(user=usr)
        if usr.is_authenticated and usr_job_info.isManager:
            pass
        else:
            return redirect('core:index')

        return super().dispatch(request, *args, **kwargs)

class LoginView(FormView):
    template_name = 'core/login.html'
    form_class = LoginForm
    success_url = '/admincrud'

    def form_valid(self, form):
        uname = form.cleaned_data['username']
        pword = form.cleaned_data['password']

        user = authenticate(username=uname, password=pword)
        self.thisuser = user
        if user is not None:
            login(self.request, user)
        else:
            return render(self.request, self.template_name, {
                'error': 'your username doesnot exist',
                'form': form
            })
        return super().form_valid(form)

@login_required(login_url='/login')
def index(request):
	# checking if employee information are updated
	EPIRecord = EmployeePersonalInfo.objects.filter(user= request.user)
	
	if not EPIRecord:
		messages.info(request, f'Please update your personal information.')
		return redirect('core:add-personal-info')
	EEIRecord = EmployeeEducationInfo.objects.filter(user= request.user)
	if not EEIRecord:
		messages.info(request, f'Please update your educational information.')
		return redirect('core:add-education-info')
	EExIRecord = EmployeeExperienceInfo.objects.filter(user= request.user)
	if not EExIRecord:
		messages.info(request, f'Please update your experience information.')
		return redirect('core:add-experience-info')

	isManager = False
	EJI = EmployeeJobInfo.objects.filter(user = request.user)
	
	if EJI and EJI[0].isManager == True:
		isManager = True

	tasks = Task.objects.filter(assigned_to = request.user)

	assigned_tasks = tasks.filter(is_accepted = False).filter(is_rejected = False)
	accepted_tasks = tasks.filter(is_accepted = True).filter(submitted = False)
	rejected_tasks = tasks.filter(is_rejected = True)
	submitted_tasks = TaskReview.objects.filter(submitted_by = request.user)
	
	context = {
		'assigned_tasks' : assigned_tasks,
		'total_assigned_tasks' : assigned_tasks.count(),
		'accepted_tasks' : accepted_tasks,
		'total_accepted_tasks' : accepted_tasks.count(),
		'rejected_tasks' : rejected_tasks,
		'total_rejected_tasks' : rejected_tasks.count(),
		'submitted_tasks' : submitted_tasks,
		'total_submitted_tasks' : submitted_tasks.count(),

	}

	return render(request, 'core/index.html', context)

# EmployeePersonalInfo(EPI) create view
class EPICreateView(CreateView, LoginRequiredMixin):
	model = EmployeePersonalInfo
	fields = [ 'fullname', 'gender', 'age', 'address', 'phone_number']
	template_name = 'core/epicreate.html'
	success_url = '/'

	def form_valid(self, form):
		form.instance.user = self.request.user
		return super().form_valid(form)

# EmployeeEducationInfo(EEI) create view
class EEICreateView(CreateView, LoginRequiredMixin):
	model = EmployeeEducationInfo
	fields = [ 'university', 'degree', 'faculty', 'graduatation_year']
	template_name = 'core/eeicreate.html'
	success_url = '/'

	def form_valid(self, form):
		form.instance.user = self.request.user
		return super().form_valid(form)

# EmployeeExperienceInfo(EExI) create view
class EExICreateView(CreateView, LoginRequiredMixin):
	model = EmployeeExperienceInfo
	fields = [ 'experience_in_years', 'no_of_previous_company', 'jobtitle_at_previous']
	template_name = 'core/eexicreate.html'
	success_url = '/'

	def form_valid(self, form):
		form.instance.user = self.request.user
		return super().form_valid(form)

@login_required(login_url='/login')
def profile(request):
	# checking if employee information is updated
	EPIRecord = EmployeePersonalInfo.objects.filter(user= request.user)
	if not EPIRecord:
		messages.info(request, f'Please update your personal information.')
		return redirect('core:add-personal-info')

	personal_info = EmployeePersonalInfo.objects.get(user=request.user)
	try:
		job_info = EmployeeJobInfo.objects.get(user=request.user)
	except:
		job_info = {
			'department' : 'N/A',
			'job_title' : 'N/A',
			'rank' : 'N/A',
			'working_hours' : 'N/A',
			'roles' : 'N/A',
			'Pay_Grade' : 'N/A'
		}
	user_info = request.user

	context = {
		'personal_info' : personal_info,
		'job_info' : job_info, 
		'user_info' : user_info
	}
	return render(request, 'core/profile.html', context)

# EmployeePersonalInfo(EPI) Update view
class EPIUpdateView(UpdateView, LoginRequiredMixin,UserPassesTestMixin):
	model = EmployeePersonalInfo
	fields = ['fullname', 'gender', 'age', 'address', 'phone_number']
	template_name = 'core/epicreate.html'
	success_url = '/profile'

	def user_passes_test(self, request):
		if request.user.is_authenticated:
		    self.object = self.get_object()
		    return self.object.user == request.user
		return False

	def dispatch(self, request, *args, **kwargs):
		if request.user.is_authenticated:
	
			EmployeePersonalInfo_data = EmployeePersonalInfo.objects.filter(user=self.request.user)
			
			if not self.user_passes_test(request):
				if not EmployeePersonalInfo_data:
					return redirect('core:add-personal-info')
				return redirect('core:update-personal-info', pk=EmployeePersonalInfo_data[0].pk)
		
		return super(EPIUpdateView, self).dispatch(
	    request, *args, **kwargs)

# EmployeeProfilePics(EPI) Update view
class ProfilePicIUpdateView(UpdateView, LoginRequiredMixin,UserPassesTestMixin):
	model = EmployeePersonalInfo
	fields = ['image']
	template_name = 'core/epicreate.html'
	success_url = '/profile'

	def user_passes_test(self, request):
		if request.user.is_authenticated:
		    self.object = self.get_object()
		    return self.object.user == request.user
		return False

	def dispatch(self, request, *args, **kwargs):
		if request.user.is_authenticated:
			EmployeePersonalInfo_data = EmployeePersonalInfo.objects.filter(user=self.request.user)
			
			if not self.user_passes_test(request):
				if not EmployeePersonalInfo_data:
					return redirect('core:add-personal-info')
				return redirect('core:update-profile-pic', pk=EmployeePersonalInfo_data[0].pk)
		return super(ProfilePicIUpdateView, self).dispatch(
	    request, *args, **kwargs)

# Details of a task
class TaskDeailView(DetailView, LoginRequiredMixin):
	model = Task
	template_name = 'core/task_details.html'
	context_object_name = 'task'

# Details of a task review
class TaskReviewDeailView(DetailView, LoginRequiredMixin):
	model = TaskReview
	template_name = 'core/review_details.html'
	context_object_name = 'review'

class ManagerDashboard(LoginRequiredMixin, ManagerRequiredMixin, ListView):
	model = Task
	template_name = 'core/manager_dashboard.html'
	context_object_name = 'tasks'

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		tasks = Task.objects.filter(created_by = self.request.user)
		
		context['created_tasks'] = tasks.filter(assigned_to = None)
		context['assigned_tasks'] = tasks.filter(submitted = False).filter(is_accepted = False).filter(is_rejected = False).exclude(assigned_to = None)
		context['accepted_tasks'] = tasks.filter(is_accepted = True).filter(submitted = False)
		context['rejected_tasks'] = tasks.filter(is_rejected = True)
		context['submitted_tasks'] = TaskReview.objects.filter(task__created_by = self.request.user)		

		return context	

class DepartmentInformation(LoginRequiredMixin, ManagerRequiredMixin, ListView):
	model = Department
	template_name = 'core/department_info.html'

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)

		job_info = EmployeeJobInfo.objects.get(user = self.request.user)
		if job_info.isManager == True:    
			department = job_info.department
			user_info = EmployeeJobInfo.objects.filter(department = department)
			employee_info = []
			for user in user_info:
				info = EmployeePersonalInfo.objects.get(user =user.user)
				
				emp_info = {
					'user_pk' : user.user.pk,
					'username' : info.user.username,
					'fullname' : info.fullname,
					'age' : info.age,
					'address' : info.address,
					'pk' : info.pk,
					'department' : department,
					'job_title' : user.job_title,
					'rank' : user.rank,
					'working_hours' : user.working_hours,
					'roles' : user.roles,
					'isManager' : user.isManager,
				}
				employee_info.append(emp_info)
			context['employee_info'] = employee_info
			context['department'] = department

			return context
		else:
			context['error_message'] = 'You are not authorized to visit this page.'
			return context

class TaskList(LoginRequiredMixin, ListView):
	model = Task
	template_name = 'core/task_list.html'

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)

		job_info = EmployeeJobInfo.objects.get(user = self.request.user)
		task_user = User.objects.get(pk = self.kwargs['pk'])

		if job_info.isManager == True or self.request.user == task_user:
			tasks = Task.objects.filter(assigned_to = task_user).order_by('created_at')

			context['tasks'] = tasks

core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Performance Evaluation System</title>

	<link rel="stylesheet" type="text/css" href="{% static 'core/bootstrap.min.css' %}">

	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css">

	<link rel="stylesheet" type="text/css" href="{% static 'core/style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'assignment/style.css' %}">

	<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<script src="{% static 'core/javascript/bootstrap.min.js' %}"></script>

	{% block head %}
	{% endblock %}

</head>
<body>

	{% if user_is_authenticated %}
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
          <!--   <a class="navbar-brand" href="#">
                <i class="fa fa-snowflake" aria-hidden="true"></i>
                FYP
            </a> -->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
            	<ul class="navbar-nav">
            		
            	</ul>
   
                 <ul class="navbar-nav ml-auto">
                      <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          {{ user_fullname }}
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                          <a class="dropdown-item" href="{% url 'core:profile' %}">Profile</a>
                          <div class="dropdown-divider"></div>
                          <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                        </div>
                      </li>

                </ul>
            </div>
        </div>
    </nav>
    <br>
    <div class="nav-side-menu">
    <div class="brand">FYP</div>
    <i class="fa fa-bars fa-2x toggle-btn" data-toggle="collapse" data-target="#menu-content"></i>
  
        <div class="menu-list">
  
            <ul id="menu-content" class="menu-content collapse out">
                <li>
                  <a href="{% url 'core:index' %}">
                  <i class="fas fa-tachometer-alt"></i>Dashboard
                  </a>
                </li>

                <li  data-toggle="collapse" data-target="#products" class="collapsed active">
                  <a href="#"><i class="fas fa-table fa-lg"></i> Tasks </a>
                </li>
                <ul class="sub-menu collapse" id="products">
                    <li><a href="{% url 'core:task-list' request.user.pk %}">Overview</a></li>
                </ul>


                {% if user_is_admin %}
	                <li data-toggle="collapse" data-target="#service" class="collapsed">
	                  <a href="#"><i class="fa fa-globe fa-lg"></i> Admin</a>
	                </li>  
	                <ul class="sub-menu collapse" id="service">
	                  <li><a href="{% url 'assignment:admin-index' %}">Dashboard</a></li>
	                  <li><a href="{% url 'assignment:department-list' %}">Department List</a></li>
	                  <li><a href="{% url 'createMode:jobinfo-create' %}">Create Job Info</a></li>
	                </ul>
                {% endif %}

                {% if user_is_manager %}
	                <li data-toggle="collapse" data-target="#new" class="collapsed">
	                  <a href="#"><i class="fa fa-car fa-lg"></i> Manager </a>
	                </li>
	                <ul class="sub-menu collapse" id="new">
	                  <li><a href="{% url 'core:manager-dashboard' %}">Dashboard</a></li>
	                  <li><a href="{% url 'createMode:create-task' %}">Create Task</a></li>
	                  <li><a href="{% url 'core:department-information' %}">Department Details</a></li>
	                </ul>
                {% endif %}


                 <li>
                  <a href="{% url 'core:profile' %}">
                  <i class="fa fa-user fa-lg"></i> Profile
                  </a>
                  </li>

                 <li>
                  <a href="{% url 'core:emp-performance' request.user.pk %}">
                  <i class="fa fa-users fa-lg"></i> Performance
                  </a>
                </li>
            </ul>
     </div>
</div>

{% else %}
	<nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="#">
                <i class="fa fa-snowflake" aria-hidden="true"></i>
                Performance Evaluation System
            </a>
            </div>           
        </nav>
{% endif %}

	
	<div class="main-content">

		{% block content %}

		{% endblock %}

	</div>

   

</body>
</html>

core/templates/core/department_info.html
{% extends 'core/base.html' %}

{% block content %}

	<h1>{{ department.name }}</h1>

	<h4 style="text-align: center;"><small> {{department.description }} </small></h4>

	<table>
		<tr>
			<th>username</th>
			<th>Full Name</th>
			<th>Department</th>
			<th>Job title</th>
			<th>Rank</th>
			<th>Role</th>
			<th>Hours</th>
			<th>isManager</th>
			<th>Assign Task</th>
		</tr>
			{% for object in employee_info %}
				<tr>
			    	<td> <a href="{% url 'core:task-list' object.user_pk %}">
			    		{{ object.username}}
			    	</a></td>
			    	<td> {{ object.fullname }}</td>
			    	<td>{{ object.department }}</td>
			    	<td>{{ object.job_title }}</td>
			    	<td> {{ object.rank }} </td>
			    	<td> {{ object.roles }} </td>
			    	<td> {{ object.working_hours }} </td>
			    	<td> {{ object.isManager }}</td>
			    	<td>
			    		<a class="check" href="{% url 'createMode:user-create-task' object.user_pk %}"><i class="fas fa-plus" title="Assign Task"></i></a>
			    	</td>
			    </tr>
			{% endfor %}
		
	</table>

{% endblock %}

core/templates/core/eeicreate.html
{% extends 'core/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
	
	<div style="margin-left: 20%; margin-right: 20%; text-align: center">
		{% if messages %}
       		{% for message in messages %}

     			<div class="alert alert-{{ message.tags }}">
         			{{ message }}
				</div>

         	{% endfor %}
        {% endif %}
	</div>

	<div class="infoupdateform container">
		<h3>Educationsl Information </h3>
		<form method="POST" class="form-group">
			{% csrf_token %}
			{{ form|crispy }}
			<button type="submit" class="btn btn-success">Update</button>
		</form>
	</div>	

{%  endblock %}

core/templates/core/login.html
<form method = "POST">
    {% csrf_token %}
    <div class="login">
       <h1>Login</h1>	
       <form>
       	{% csrf_token %}
        {{ form.as_p }}
       </form>
        <button>Login</button>
    </div>	
</form>

core/templates/core/task_details.html
{% extends 'core/base.html' %}

{% block content %}

	<div class="container">

		<div style="margin-left: 20%; margin-right: 20%; text-align: center">
			{% if messages %}
       			{% for message in messages %}

     				<div class="alert alert-{{ message.tags }}">
         				{{ message }}
					</div>

         		{% endfor %}
        	{% endif %}
		</div>	

		<h1>Task Review Details</h1>

		<div class="row">
			<div class="col">
				<h3>Task Details:</h3>
				<h5><strong>Title:</strong> <small>{{ task.title }}</small></h5>
				<h5> <strong>Description:</strong>  <small>{{ task.description }}</small></h5>
				<h5><strong>Provided Resources: </strong> <small>
					{% if task.resources %}
		    			<a href="{{ task.resources.url }}">{{ task.resources.name }}</a>
		    		{% else %}
		    			N/A
		    		{% endif %}
				</small></h5>
				<h5><strong>Assigned to:</strong> <small>{{ task.assigned_to }}</small></h5>
				<h5><strong>Department: </strong><small>{{ task.department }}</small></h5>
				<h5><strong>Deadline: </strong> <small>{{ task.deadline }}</small></h5>
		
				<h5><strong>Total Points: </strong> <small>{{ task.total_points }}</small></h5>
			</div>
			<div class="col">
				<h3></h3>
				{% if request.user == task.assigned_to %}
					{% if task.submitted and task.reviewed %}
						<a href="{% url 'core:task-review-details' task.review_id %}" type="button" class="btn btn-success">View Review</a><br>
					{% elif task.submitted and task.reviewed == False %}
						<a type="button" class="btn btn-warning">Review Pending</a><br>
					{% else %}
						{% if task.is_accepted %}
							<a type="button" class="btn btn-success" href="{% url 'createMode:submit-task' task.pk %}">Submit Task</a><br>
						{% elif task.is_rejected %}
							<a  type="button" class="btn btn-warning">Task Rejeced</a> <br><br>
						{% else %}
							<a href="{% url 'createMode:accept-task' task.pk %}" type="button" class="btn btn-success">Accept Task</a> <br>
							<a href="{% url 'createMode:reject-task' task.pk %}" type="button" class="btn btn-warning">Reject Task</a><br>
						{% endif %}
						
					{% endif %}
				{% endif %}

				{% if user_is_manager %}
					{% if task.created_by == request.user %}
						{% if task.assigned_to == None %}
							<a href="{% url 'createMode:assign-task' task.pk %}" type="button" class="btn btn-success"> Assign Task</a> <br>
							<a href="{% url 'createMode:update-task' task.pk %}" type="button" class="btn btn-success"> Update Task</a> <br>
						{% elif task.submitted and task.reviewed %}
							<a href="{% url 'core:task-review-details' task.review_id %}" type="button" class="btn btn-success">View Review</a> <br>
							<a href="{% url 'createMode:task-review' task.review_id %}" type="button" class="btn btn-warning">Update Review</a><br>
						{% elif task.submitted and task.reviewed == False %}
							<a href="{% url 'createMode:task-review' task.review_id %}" type="button" class="btn btn-warning">Review Task</a><br>
						{% elif task.is_rejected %}
							<a type="button" class="btn btn-warning" href="{% url 'createMode:rejected-feedback' task.reject_feedback_id %}">Rejection Details</a><br>
						{% elif task.is_accepted %}
							<a  type="button" class="btn btn-warning">Submission Pending</a><br>
						{% elif task.is_accepted %}
							<a  type="button" class="btn btn-warning">Submission Pending</a><br>
						{% elif task.is_accepted == False and task.is_rejected == False %}
							<a  type="button" class="btn btn-warning">Acknowledgement Pending</a><br>
						{% endif %}

					{% endif %}
				{% endif %}
				

				
			</div>
			
		</div>
	</div>


{% endblock %}